baseURL = "https://shafiqaiman.com"
theme = "LoveIt"
title = "SHAFIQAIMAN"
languageCode = "en"
languageName = "English"
hasCJKLanguage = false
paginate = 12
enableRobotsTXT = true
enableGitInfo = false
enableEmoji = false
# ignore some build errors
ignoreErrors = ["error-remote-getjson", "error-missing-instagram-accesstoken"]

# Author config
[author]
  name = "SHAFIQAIMAN"
  email = ""
  link = "https://shafiqaiman.com"

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "posts"
    pre = "<i class=\"fa-solid fa-book\"></i>"
    post = ""
    name = ""
    url = "/posts/"
    title = "Posts"
  [[menu.main]]
    weight = 2
    identifier = "tags"
    pre = "<i class=\"fa-solid fa-tags\"></i>"
    post = ""
    name = ""
    url = "/tags/"
    title = "Tags"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    pre = "<i class=\"fa-solid fa-folder\"></i>"
    post = ""
    name = ""
    url = "/categories/"
    title = "Categories"  

[params]
  defaultTheme = "dark"
  gitRepo = ""
  fingerprint = ""
  dateFormat = "02-01-2006"
  title = "SHAFIQAIMAN"
  description = "shafiqaiman.com is a cybersecurity/ethical hacking website that focus on publishing of writeup in HacktheBox, Tryhackme and other online CTF (capture the flag) challenge."
  images = ["/logo.png"]

  # Header config
  [params.header]
    desktopMode = "fixed"
    mobileMode = "auto"
    [params.header.title]
      logo = ""
      name = "SH∆FIQ∆IM∆N"
      pre = ""
      post = ""
      typeit = false

  # Footer config
  [params.footer]
    enable = true
    custom = ""
    hugo = false
    copyright = true
    author = true
    since = 2021
    icp = ""
    license = ""

  #  Section (all posts) page config
  [params.section]
    paginate = 20
    dateFormat = "02-01"
    rss = 10

  #  List (category or tag) page config
  [params.list]
    paginate = 20
    dateFormat = "02-01"
    rss = 10

  #  App icon config
  [params.app]
    title = "SHAFIQAIMAN"
    noFavicon = false
    svgFavicon = ""
    themeColor = "#ffffff"
    iconColor = "#5bbad5"
    tileColor = "#da532c"

  #  Search config
  [params.search]
    enable = true
    type = "lunr"
    contentLength = 4000
    placeholder = ""
    maxResultLength = 10
    snippetLength = 30
    highlightTag = "em"
    absoluteURL = false
    [params.search.algolia]
      index = ""
      appID = ""
      searchKey = ""

  # Home page config
  [params.home]
    rss = 10
    [params.home.profile]
      enable = true
      gravatarEmail = ""
      avatarURL = "/images/avatar.jpg"
      title = "SH∆FIQ∆IM∆N"
      subtitle = "Nothing much..."
      typeit = false
      social = true
      disclaimer = ""
    # Home page posts
    [params.home.posts]
      enable = true
      paginate = 6
      defaultHiddenFromHomePage = false

  # Social config about the author
  [params.social]
    GitHub = "shafiqaimanx"
    Twitter = "_shafiqaiman_"
    HackTheBox = "483104"
    RSS = true

  #  Page global config
  [params.page]
    hiddenFromHomePage = false
    hiddenFromSearch = false
    twemoji = false
    lightgallery = false
    ruby = true
    fraction = true
    fontawesome = true
    linkToMarkdown = false
    rssFullText = false
    [params.page.toc]
      enable = true
      keepStatic = false
      auto = true
    [params.page.math]
      enable = false
      inlineLeftDelimiter = ""
      inlineRightDelimiter = ""
      blockLeftDelimiter = ""
      blockRightDelimiter = ""
      copyTex = true
      mhchem = true
    [params.page.code]
      copy = true
      maxShownLines = 50
    [params.page.mapbox]
      accessToken = ""
      lightStyle = "mapbox://styles/mapbox/light-v10?optimize=true"
      darkStyle = "mapbox://styles/mapbox/dark-v10?optimize=true"
      navigation = false
      geolocate = false
      scale = false
      fullscreen = false
    [params.page.share]
      enable = true
      Twitter = true
      Linkedin = true
      HackerNews = true
      Reddit = true
      Facebook = false
      Line = false
      Weibo = false
    [params.page.comment]
      enable = false
      [params.page.comment.disqus]
        enable = false
        shortname = ""
      [params.page.comment.gitalk]
        enable = false
        owner = ""
        repo = ""
        clientId = ""
        clientSecret = ""
      [params.page.comment.valine]
        enable = false
        appId = ""
        appKey = ""
        placeholder = ""
        avatar = "mp"
        meta= ""
        pageSize = 10
        lang = ""
        visitor = false
        recordIP = false
        highlight = false
        enableQQ = false
        serverURLs = ""
        emoji = ""
      [params.page.comment.facebook]
        enable = false
        width = "100%"
        numPosts = 10
        appId = ""
        languageCode = ""
      [params.page.comment.telegram]
        enable = false
        siteID = ""
        limit = 5
        height = ""
        color = ""
        colorful = false
        dislikes = false
        outlined = false
      [params.page.comment.commento]
        enable = false
      [params.page.comment.utterances]
        enable = false
        repo = ""
        issueTerm = "pathname"
        label = ""
        lightTheme = "github-light"
        darkTheme = "github-dark"
      [params.page.comment.giscus]
        enable = false
        repo = ""
        repoId = ""
        category = "Announcements"
        categoryId = ""
        lang = ""
        mapping = "pathname"
        reactionsEnabled = "1"
        emitMetadata = "0"
        inputPosition = "bottom"
        lazyLoading = false
        lightTheme = "light"
        darkTheme = "dark"
    [params.page.library]
      [params.page.library.css]
      [params.page.library.js]
    [params.page.seo]
      images = []
      [params.page.seo.publisher]
        name = ""
        logoUrl = ""

  #  TypeIt config
  [params.typeit]
    speed = 100
    cursorSpeed = 1000
    cursorChar = "|"
    duration = -1

  # Site verification code config for Google/Bing/Yandex/Pinterest/Baidu
  [params.verification]
    google = ""
    bing = ""
    yandex = ""
    pinterest = ""
    baidu = ""

  #  Site SEO config
  [params.seo]
    image = ""
    thumbnailUrl = ""

  #  Analytics config
  [params.analytics]
    enable = false
    # Google Analytics
    [params.analytics.google]
      id = ""
      anonymizeIP = true
    # Fathom Analytics
    [params.analytics.fathom]
      id = ""
      server = ""
    [params.analytics.plausible]
      dataDomain = ""
    [params.analytics.yandexMetrica]
      id = ""

  #  Cookie consent config
  [params.cookieconsent]
    enable = false
    [params.cookieconsent.content]
      message = ""
      dismiss = ""
      link = ""

  #  CDN config for third-party library files
  [params.cdn]
    # CDN data file name, disabled by default
    # ["jsdelivr.yml"]
    # located in "themes/LoveIt/assets/data/cdn/" directory
    # you can store your own data files in the same path under your project:
    # "assets/data/cdn/"
    data = ""

  #  Compatibility config
  [params.compatibility]
    polyfill = false
    objectFit = false

# Markup related config in Hugo
[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = true
    lineNos = true
    lineNumbersInTable = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.extensions]
      definitionList = true
      footnote = true
      linkify = true
      strikethrough = true
      table = true
      taskList = true
      typographer = true
    [markup.goldmark.renderer]
      unsafe = true
  # Table Of Contents settings
  [markup.tableOfContents]
    startLevel = 2
    endLevel = 6

# Sitemap config
[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5

# Permalinks config
#[Permalinks]
  # posts = ":year/:month/:filename"
  # posts = ":filename"

# Privacy config
[privacy]
  [privacy.googleAnalytics]
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true

# Options to make output .md files
[mediaTypes]
  [mediaTypes."text/plain"]
    suffixes = ["md"]

# Options to make output .md files
[outputFormats.MarkDown]
  mediaType = "text/plain"
  isPlainText = true
  isHTML = false

# Options to make hugo output files
[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML", "MarkDown"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  #taxonomyTerm = ["HTML"]
